name: CI

on:
    push:
        branches: master
    pull_request:
        branches: master

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Check python code formatting
          run: |
            pip install black
            black --check .

        - name: Check compliance with pep8, pyflakes and circular complexity
          run: |
            pip install flake8
            flake8 .
